version: "3.9"
services:
  slide-show:   # "slide-show"を任意の名前に変更
    container_name: slide-show    # "slide-show"を任意の名前に変更
    build:
      context: .
      dockerfile: Dockerfile
      target: prd
    tty: true
    ports:
      - "8501:8501"