version: "3.9"
services:
  slide-show-dev:   # "slide-show"を任意の名称に変更
    container_name: slide-show-dev    # "slide-show"を任意の名称に変更
    build:
      context: ../
      dockerfile: Dockerfile
      target: dev
    tty: true
    volumes:
      - ../:/workspace
